// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0DEjixFPBUMX4VUcoECWqERsaTmck2Ug',
    appId: '1:115344954306:web:5c0aacf2356f46358fbc5b',
    messagingSenderId: '115344954306',
    projectId: 'flutter-order-tracking',
    authDomain: 'flutter-order-tracking.firebaseapp.com',
    storageBucket: 'flutter-order-tracking.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7JP975a0V7ybZPaRNK-Ln-7ymOJj82xc',
    appId: '1:115344954306:android:280c3a3f129d711c8fbc5b',
    messagingSenderId: '115344954306',
    projectId: 'flutter-order-tracking',
    storageBucket: 'flutter-order-tracking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU22SH_EcohOLzRsTXU-rwa8TcdNt_vYg',
    appId: '1:115344954306:ios:a8d463d900f3cab28fbc5b',
    messagingSenderId: '115344954306',
    projectId: 'flutter-order-tracking',
    storageBucket: 'flutter-order-tracking.firebasestorage.app',
    iosBundleId: 'com.example.flutterOrderTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU22SH_EcohOLzRsTXU-rwa8TcdNt_vYg',
    appId: '1:115344954306:ios:a8d463d900f3cab28fbc5b',
    messagingSenderId: '115344954306',
    projectId: 'flutter-order-tracking',
    storageBucket: 'flutter-order-tracking.firebasestorage.app',
    iosBundleId: 'com.example.flutterOrderTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0DEjixFPBUMX4VUcoECWqERsaTmck2Ug',
    appId: '1:115344954306:web:412c389ac8282e958fbc5b',
    messagingSenderId: '115344954306',
    projectId: 'flutter-order-tracking',
    authDomain: 'flutter-order-tracking.firebaseapp.com',
    storageBucket: 'flutter-order-tracking.firebasestorage.app',
  );

}